### ISSUE TITLE
Use @stoplight/json-ref-resolver instead of @apidevtools/json-schema-ref-parser

### ISSUE THREAD

**Issue by kennethaasan** [asyncapi/bundler#146]
#### Reason/Context

The parser has already done this change because @apidevtools/json-schema-ref-parser does not have a maintainer.

**Comment by derberg** [comment]
Hey, just for the context in case you are not aware

The stoplight resolver is archived project https://github.com/stoplightio/json-ref-resolver and tbh parser should never start using it and hope maintainers will drop it -> https://github.com/asyncapi/parser-js/issues/761

afaik https://github.com/APIDevTools/json-schema-ref-parser has a new maintainer that after official call out for maintainers joined and even rewrote the project to TS.

**Comment by kennethaasan** [comment]
That's awesome. I wasn't aware and just spotted the difference. I commented https://github.com/asyncapi/parser-js/issues/761

**Comment by derberg** [comment]
Thanks @kennethaasan !
