### ISSUE TITLE
@asyncapi/bundler vs asyncapi-bundler

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/bundler#15]
#### Reason/Context
All other libraries all publish under AsyncAPI published under `@asyncapi/xxx` however this repository does not 🤔 Is there a specific reason for it?

**Comment by derberg** [comment]
@Souvikns is checking if some final fixes need to be done before we publish, this is why it is not there yet

**Comment by Souvikns** [comment]
I have changed the name to `@asyncapi/bundler` will update the documentation accordingly. 

https://github.com/asyncapi/bundler/blob/649eae45b53690d39d61d54c024be1055561f5ef/package.json#L2

**Comment by derberg** [comment]
@asyncapi/bundler 0.1.0 is out in the wild
closing...
