### ISSUE TITLE
Remove usage of Parser, validation and update docs

### ISSUE THREAD

**Issue by derberg** [asyncapi/bundler#26]
> This issue is for https://www.openforce.tech/ participants. If you do not participate in this even please pick up other issue from this repo, there is plenty of help needed 😄 

#### Reason/Context

Bundler like all other tools we have does not need to perform validation (have a look at this description of diff https://github.com/asyncapi/diff#usage). Bundler like others had the main goal to be used by CLI and Studio, where validation/parsing/dereferencing is already provided or should be as dependencies are there already.

#### Description
- remove parser dependency, it can also be a devdependency in case of tests
- bundler should get already parsed (validated) and dereferenced document as input
- update docs

> This issue is for https://www.openforce.tech/ participants. If you do not participate in this even please pick up other issue from this repo, there is plenty of help needed 😄 

@Souvikns pinging you so you are aware

**Comment by meghagangadhar13** [comment]
Hi, I am Meghana , a contributor to OpenForce 2022. I would like to work on this issue.

**Comment by Souvikns** [comment]
sure @meghagangadhar13 go ahead 👍🏻 , let me know if you need any help

**Comment by derberg** [comment]
@meghagangadhar13 do you want to continue working on this one? I know OpenForce ended but if you are still interested and you were delayed by exams, we can still give you some time for this one

**Comment by Souvikns** [comment]
@meghagangadhar13 do you have time for this? I am thinking of adding some new features and this is blocking me, I would be happy to take this from your hand.
