### ISSUE TITLE
Cannot bundle documents with different base paths

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/bundler#35]
#### Describe the bug
I have the current folder setup:
```
definitions
  asyncapi.json
  components
    messages
       ...
bundler
  bundlerScript.js
```

And standing inside the `bundler` dir executing `bundlerScript.js` it is unable to locate the references for example messages as `./components/messages/myMessage.json` that `asyncapi.json` uses.

#### Expected behavior
Expected the setup to work.

I dont quite understand why there is a custom dereference in place before parsing the documents? Otherwise, I could utilize the following custom parser. Although a bit of a hack as there is no real docs what is expected from `parser` option.

```js
  const bundledDocument = await bundler(
    fileContents,
    {
      parser: {
        parse: (fileContent) => {
          const p = path.resolve(__dirname, '../../definitions')
          return parse(fileContent, {path: p})
        }
      }
    }
  );
```

**Comment by Souvikns** [comment]
the `  bundlerScript.js` has to be in the same folder where the definitions are. I could not find any way to pass basepath in `json-schema-ref-parser`, currently, the path resolves relatively. 

Also according to https://github.com/asyncapi/bundler/issues/26 we won't parse or validate the document.

**Comment by jonaslagoni** [comment]
> the ` bundlerScript.js` has to be in the same folder where the definitions are. I could not find any way to pass basepath in `json-schema-ref-parser`, currently, the path resolves relatively.

With the current setup, yes that is required 🙂 

> Also according to #26 we won't parse or validate the document.

That would definitely fix this issue yes 🙂

**Comment by jonaslagoni** [comment]
Still relevant

**Comment by aeworxet** [comment]
When auditing open issues, Bundler of version v0.3.7 was found to successfully dereference
```
./messages.yaml#/messages/UserSignedUp
../messages.yaml#/messages/UserSignedUp
../src/messages.yaml#/messages/UserSignedUp
```
Closing the issue.

**Comment by jonaslagoni** [comment]
This issue is not solved, still have the same problem, where there is no way to set the base URL for where references should be resolved.

The current bundle logic still looks for local references in the directory you execute the script from. Without a basedir option this issue will never be solved.

**Comment by jpdias** [comment]
Facing the same issue when trying to use the bundler as part of a pipeline. Passing the basePath as an argument for referenced relative paths would address the issue. For now we are doing a workaround by using the `process.chdir` to the folder where the main AsyncAPI yml is located, do the bundling, and then change back.

**Comment by Souvikns** [comment]
Added a solution with https://github.com/asyncapi/bundler/pull/148
