### ISSUE TITLE
Only `bundle` function should be exposed as part of public API

### ISSUE THREAD

**Issue by derberg** [asyncapi/bundler#70]
#### Describe the bug
When you go to https://github.com/asyncapi/bundler/blob/master/API.md#functions you see some internal functions in the API that users can use. But we should expose only `bundle`

#### Expected behavior
All functions other than `bundle` should be annotated as private, so they do not show up in the API

**Comment by toukirkhan** [comment]
@derberg only the function sections needs to be annotated right?

**Comment by derberg** [comment]
Afaik @aeworxet is working on this one already.
I can mark https://github.com/asyncapi/generator/issues/538 if you want, pretty nifty and super useful feature to add
