### ISSUE TITLE
last release is broken without `lib` dir

### ISSUE THREAD

**Issue by derberg** [asyncapi/bundler#75]
Last release is not usable. Package is published without code

👇🏼 is what we see after package installation

<img width="341" alt="Screenshot 2022-10-13 at 09 52 32" src="https://user-images.githubusercontent.com/6995927/195536286-94700609-2e69-4d64-a15c-2a0f083e3921.png">

I think it might be because of https://github.com/asyncapi/bundler/blob/master/package.json#L37

I think it should say `"/lib"` and not `lib/`
I do not see any other reason why it is not really published to npm.

`"main": "lib/index.js"` entrypoint is correct. It's just that the index file do not exist in the package

**Comment by toukirkhan** [comment]
@derberg can I look into this?

**Comment by derberg** [comment]
@toukirkhan please go ahead

**Comment by derberg** [comment]
tip: you can test it locally, if your fix works by running `npm publish --dry-run`, if I remember the command correct 😄 

if terminal will print only 👇🏼 
```
npm notice === Tarball Contents === 
npm notice 11.4kB LICENSE     
npm notice 7.1kB  README.md   
npm notice 3.0kB  package.json
npm notice === Tarball Details === 
```

then it is not fixed.
it is fixed if `index.js` will be listed too

**Comment by toukirkhan** [comment]
alright @derberg working on this one!!

**Comment by toukirkhan** [comment]
@derberg am using npm publish --dry -run it only shows package.json in tarball contents

**Comment by derberg** [comment]
@toukirkhan can you show full log, please, and what modifications you already did

**Comment by toukirkhan** [comment]
yeah am attaching the screenshots @derberg

**Comment by toukirkhan** [comment]
![image](https://user-images.githubusercontent.com/88899011/195591381-d5b01c10-7dd2-4ae9-a414-f960e995b0a8.png)

I have changed "lib/" to "/lib"

**Comment by toukirkhan** [comment]
also it has shown the tarball contents you mentioned above once

**Comment by derberg** [comment]
strange you see only `package.json`

anyway, I forgot to tell you that you need to install bundler `npm i` and then run `npm run build` to actually generate `lib` dir first. Publish dry run do not show `lib` probably because you do not have it there on a local drive

**Comment by toukirkhan** [comment]
I have did the same steps

**Comment by derberg** [comment]
ok 🤔 , can you share, like drop the view of the directory from which you run `npm publish`?

**Comment by toukirkhan** [comment]
yeah sure

**Comment by toukirkhan** [comment]
![image](https://user-images.githubusercontent.com/88899011/195628612-53ad1572-b907-4230-813e-86a1a370d57e.png)
@derberg

**Comment by toukirkhan** [comment]
I am running it in the node_modules directory

**Comment by toukirkhan** [comment]
@derberg okay I got it changed lib but it still does not show index.html

**Comment by derberg** [comment]
you mean `index.js` right?
can you show latest logs?

**Comment by toukirkhan** [comment]
![image](https://user-images.githubusercontent.com/88899011/195637679-d5e342c3-258a-40f5-9ac6-b1b1a044a76f.png)

**Comment by toukirkhan** [comment]
> I saw that in picture your terminal says that `npm run build` doesn't exist. This is weirt. Are you sure `bundler` is the directory where you cloned the project? can you print all files you have there `ls` is command in UNIX, not sure windows

yeah sure

**Comment by Souvikns** [comment]
I think best would be if @toukirkhan you can open a PR, and we can check it.

**Comment by toukirkhan** [comment]
> I think best would be if @toukirkhan you can open a PR, and we can check it.

it won't be a great idea because it does not resolves the issue

**Comment by toukirkhan** [comment]
@derberg i did npm run build
![image](https://user-images.githubusercontent.com/88899011/195638506-1245440b-b35b-4521-8111-017007f43d86.png)

**Comment by derberg** [comment]
Ok, I think I know what the problem is

you do `ls` and other command runs from inside the `node_modules` where bundler is installed, and yes it shows that package is empty, which is wrong.

now please explain why in `bundler` directory you installed `@asyncapi/bundler`

what is exactly in `bundler` directory, main one, not `bundler\none_modules\@asyncapi\bundler`?

**Comment by derberg** [comment]
so if `C:\Users\Lenovo\Desktop\bundler` is a place where you cloned your fork

then you should do:
```
C:\Users\Lenovo\Desktop\bundler> npm i
C:\Users\Lenovo\Desktop\bundler> npm run build
C:\Users\Lenovo\Desktop\bundler> npm publish --dry-run
```

**Comment by toukirkhan** [comment]
> Ok, I think I know what the problem is
> 
> you do `ls` and other command runs from inside the `node_modules` where bundler is installed, and yes it shows that package is empty, which is wrong.
> 
> now please explain why in `bundler` directory you installed `@asyncapi/bundler`
> 
> what is exactly in `bundler` directory, main one, not `bundler\none_modules\@asyncapi\bundler`?

bundler directory is a directory in my desktop inside which I have installed the bundler

**Comment by toukirkhan** [comment]
> so if `C:\Users\Lenovo\Desktop\bundler` is a place where you cloned your fork
> 
> then you should do:
> 
> ```
> C:\Users\Lenovo\Desktop\bundler> npm i
> C:\Users\Lenovo\Desktop\bundler> npm run build
> C:\Users\Lenovo\Desktop\bundler> npm publish --dry-run
> ```

yeah finally I got this!!

**Comment by toukirkhan** [comment]
I have run the command inside the cloned bundler repo and made a dry run and it shows this
![image](https://user-images.githubusercontent.com/88899011/195644429-b8bde20c-aa38-4e76-8506-5bc17ec524a0.png)

**Comment by toukirkhan** [comment]
now where should I make the changes?

**Comment by toukirkhan** [comment]
here is the directory
![image](https://user-images.githubusercontent.com/88899011/195645114-6b8ca00a-0cd2-440f-bfa0-c8d01352c8ba.png)

**Comment by derberg** [comment]
yup, perfect. from your logs it looks like it is the fix we expect. go ahead and open up a PR

**Comment by toukirkhan** [comment]
@derberg okay cool! am opnening it rn
