### ISSUE TITLE
Add missing release script to `package.json`

### ISSUE THREAD

**Issue by derberg** [asyncapi/bundler#78]
The package is still not properly released. 
It is because after migration to TS we forgot that we need to make sure proper `lib/index.js` code is produced during the release. In other words in current release script we do not run `npm run build`

Fix is to add below script to `package.json`:
`"prepublishOnly": "npm run build"`

**Comment by derberg** [comment]
@toukirkhan hey, letting you know, in case you are still interested in helping here as part of hacktoberfest, and maybe beyond

**Comment by toukirkhan** [comment]
@derberg sure I will try to solve this.

**Comment by KeneePatel** [comment]
So, Do I just need to add  `"prepublishOnly": "npm run build"` in `package.json` and under the `"scripts"` section and make a pr ? @derberg

**Comment by derberg** [comment]
hey folks, @aeworxet just opened a PR as this is important fix that is affecting users
